name: Backend CI

on:
  push:
    branches: [ main, 'feature/*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker containers
        run: docker-compose build

      - name: Start services in background
        run: docker-compose up -d db redis rabbitmq

      - name: Wait for services to be ready
        run: |
          ./wait-for-it.sh db:5432 --timeout=60 --strict -- echo "Postgres ready"
          ./wait-for-it.sh redis:6379 --timeout=60 --strict -- echo "Redis ready"
          ./wait-for-it.sh rabbitmq:5672 --timeout=60 --strict -- echo "RabbitMQ ready"
        shell: bash

      - name: Run migrations and Django tests inside web container
        run: |
          docker-compose run --rm web bash -c "\
            echo 'Running migrations...' && \
            python manage.py migrate && \
            echo 'Running Django tests...' && \
            python manage.py test && \
            echo 'Starting temporary Celery worker for tests...' && \
            celery -A social_media_feed worker --loglevel=INFO --detach && \
            python manage.py test_celery_task && \
            echo 'Stopping Celery worker...' && \
            pkill -f 'celery' \
          "

      - name: Shut down containers
        run: docker-compose down
